name: MTTT
version: 4.0.0Alpha
main: de.melays.ttt.main
author: MeLays
softdepend: [Multiverse-Core, CrackShot, PlaceholderAPI , StatsAPI , AutoNicker]
commands:
    ttt:
        description: All informations
        usage: /<command>
    tc:
        aliases: [traitorchat , t , sc]
        description: Traitorchat
        usage: /<command>
    tshop:
        description: Shop
        usage: /<command>
    shop:
        description: Shop
        usage: /<command>
    traitor:
        description: Traitorpasses
        usage: /<command>
    detective:
        description: Detectivepass
        usage: /<command>
    role:
        description: Detectivepass
        usage: /<command>
    